### PR TITLE
Editor layout fixes

### LINKED ISSUE #1058: Port resizing functionality from themer-prototype to code-editor

### PR DESCRIPTION
**Pull request by robustdj**
* Add ability to resize code editor
* Add css editing mode to layout view

Closes #1058

### CODE REVIEW

File: packages/cardhost/app/components/code-editor.js [hunk 1]
```diff
@@ -22,13 +22,25 @@ requirejsPolyfill();
 export default class CodeEditor extends Component {
   editor; // value is set by renderEditor
 
+  constructor(...args) {
+    super(...args);
+
+    this.resizable = (this.args.resizable === true) ? true : false;
```
Comment (jenweber) [inline packages/cardhost/app/components/code-editor.js]:
```suggestion
    this.resizable = (this.args.resizable === true) ? true : false;
```

In general, I've done these kinds of assignments with getters, just as a pattern. Using the constructor works fine too.
